
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


apiVersion: gateway.apiconnect.ibm.com/v1beta1
kind: GatewayCluster
metadata:
  name: gwv6
spec:
  version: 10.0.8.4
  profile: n1xc4.m8
  imagePullSecrets:
  - apic-registry-secret
  imageRegistry: docker.io/gandigit
  apicGatewayServiceV5CompatibilityMode: false
  gatewayEndpoint:
    ingressClassName: nginx
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: rgw.111.222.333.444.nip.io
      secretName: gwv6-endpoint
  gatewayManagerEndpoint:
    ingressClassName: nginx
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: rgwd.111.222.333.444.nip.io
      secretName: gwv6-manager-endpoint
  apicGatewayServiceTLS:
    secretName: gateway-service
  apicGatewayPeeringTLS:
    secretName: gateway-peering
  mgmtPlatformEndpointCASecret:
    secretName: ingress-ca
  #mgmtPlatformEndpointSvcCASecret:
  #  secretName:  # Usually management-ca
  datapowerLogLevel: 3
  license:
    accept: true
    use: nonproduction
    license: L-HTFS-UAXYM3
  tokenManagementService:
    enabled: true
    storage:
      storageClassName: managed-premium
      volumeSize: 30Gi
  adminUser:
    secretName: datapower-admin-credentials
    # jwksUrl: https://api.myapp.nip.io/api/cloud/oauth2/certs    
  mtlsValidateClient: true
  # syslogConfig:
  #   enabled: false # if true, provide below details
  #   remoteHost: $DATAPOWER_SYSLOG_TCP_REMOTE_HOST # must be a string
  #   remotePort: $DATAPOWER_SYSLOG_TCP_REMOTE_PORT # must be an int
  #   secretName: $DATAPOWER_SYSLOG_TCP_TLS_SECRET # must be a string
